services:
    _defaults:
        autowire: true
        autoconfigure: true

    ProductBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    ProductBundle\Service\:
        resource: '../src/Service/'